### PR TITLE
Supports arm64 binaries

### PR DESCRIPTION
**Pull request by rafalstapinski**

### CODE REVIEW

**Comment by rafalstapinski** [comment]
hey @bstoutenburgh no rush but if you've got a moment and can take a peek at this - would be cool to get this merged in and up into asdf/mise to support arm64 (e.g. apple silicon) binaries

**Comment by rafalstapinski** [comment]
whoops - just realized this returns `x86_64` not `amd64`. will update

**Comment by rafalstapinski** [comment]
@bstoutenburgh no rush but if you have a moment would you be able to take a peek at this? would be cool to get this merged in and up into asdf/mise and support arm64 (e.g. apple silicon) binaries

**Comment by bstoutenburgh** [comment]
Thanks for this, I was actually considering getting an Apple device to check this.

**Pull request merged**
